DROP TABLE IF EXISTS ARTICLE;
DROP TABLE IF EXISTS USER;

CREATE TABLE user(
	id IDENTITY NOT NULL AUTO_INCREMENT, 
	name varchar(30) NOT NULL, 
	age number,
	PRIMARY KEY(id),
);

CREATE TABLE article(
	id IDENTITY NOT NULL AUTO_INCREMENT, 
	text CLOB NOT NULL, 
	color varchar(45), 
	author_id int NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY (author_id) REFERENCES user (id) ON DELETE CASCADE ON UPDATE CASCADE,
);